package com.yaxim.global.error.model;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;

@Getter
@RequiredArgsConstructor
public enum ErrorCode {
    INTERNAL_SERVER_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, "INTERNAL_SERVER_ERROR"),
    UNKNOWN_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, "UNKNOWN_ERROR"),
    INVALID_TOKEN(HttpStatus.UNAUTHORIZED, "INVALID_TOKEN"),
    TOKEN_EXPIRED_EXCEPTION(HttpStatus.UNAUTHORIZED, "TOKEN_EXPIRED_EXCEPTION"),
    ILLEGAL_REGISTRATION(HttpStatus.BAD_REQUEST, "ILLEGAL_REGISTRATION"),
    USER_HAS_NO_AUTHORITY(HttpStatus.UNAUTHORIZED, "USER_HAS_NO_AUTHORITY"),
    USER_NOT_FOUND(HttpStatus.NOT_FOUND, "USER_NOT_FOUND"),
    
    // ========== 프로젝트 관련 에러 ==========
    PROJECT_NOT_FOUND(HttpStatus.NOT_FOUND, "PROJECT_NOT_FOUND"),
    PROJECT_ACCESS_DENIED(HttpStatus.FORBIDDEN, "PROJECT_ACCESS_DENIED"),
    PROJECT_FILE_NOT_FOUND(HttpStatus.NOT_FOUND, "PROJECT_FILE_NOT_FOUND"),

    // ========== 프로젝트 검증 관련 에러 ==========
    PROJECT_NAME_TOO_LONG(HttpStatus.BAD_REQUEST, "PROJECT_NAME_TOO_LONG"),
    PROJECT_DESCRIPTION_TOO_LONG(HttpStatus.BAD_REQUEST, "PROJECT_DESCRIPTION_TOO_LONG"),
    PROJECT_DATE_RANGE_INVALID(HttpStatus.BAD_REQUEST, "PROJECT_DATE_RANGE_INVALID"),
    
    // ========== 파일 업로드 관련 에러 ==========
    FILE_SHOULD_NOT_BE_NULL(HttpStatus.BAD_REQUEST, "FILE_SHOULD_NOT_BE_NULL"),
    FILE_COUNT_EXCEEDED(HttpStatus.BAD_REQUEST, "FILE_COUNT_EXCEEDED"),
    FILE_SIZE_EXCEEDED(HttpStatus.PAYLOAD_TOO_LARGE, "FILE_SIZE_EXCEEDED"),
    FILE_FORMAT_NOT_SUPPORTED(HttpStatus.UNSUPPORTED_MEDIA_TYPE, "FILE_FORMAT_NOT_SUPPORTED"),
    FILE_TOTAL_SIZE_EXCEEDED(HttpStatus.PAYLOAD_TOO_LARGE, "FILE_TOTAL_SIZE_EXCEEDED"),
    FILE_DOWNLOAD_URL_GENERATE_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "FILE_DOWNLOAD_URL_GENERATE_FAILED" ),
    FILE_DELETE_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "FILE_DELETE_FAILED" ),
    FILE_UPLOAD_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "FILE_UPLOAD_FAILED" ),

    TOKEN_NOT_PROVIDED(HttpStatus.UNAUTHORIZED, "TOKEN_NOT_PROVIDED"),
    TEAM_NOT_FOUND(HttpStatus.NOT_FOUND, "TEAM_NOT_FOUND" ),
    OIDC_TOKEN_EXPIRED(HttpStatus.UNAUTHORIZED, "OIDC_TOKEN_EXPIRED" ),
    TEAM_MEMBER_NOT_MAPPED(HttpStatus.NOT_FOUND, "TEAM_MEMBER_NOT_MAPPED"),
    GIT_INFO_NOT_FOUND(HttpStatus.NOT_FOUND, "GIT_INFO_NOT_FOUND" ),
    GIT_EMAIL_IS_NOT_PROVIDED(HttpStatus.BAD_REQUEST, "GIT_EMAIL_IS_NOT_PROVIDED" ),;

    private final HttpStatus status;
    private final String message;
}
