version: "3.8"

services:
  redis:
    image: redis:7.2
    container_name: local-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    # 비밀번호 설정 원할 경우 아래 줄 활성화:
    # command: redis-server --requirepass mysecretpassword

volumes:
  redis-data:

