version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: my-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: yaxim
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

